using Content.Shared.AWS.Economy.Bank;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using System.Linq;
using Robust.Client.UserInterface;
using Robust.Shared.Prototypes;
using Content.Shared.Roles;

namespace Content.Client.AWS.Economy.Bank.UI.ManagementConsole.Tabs;

[GenerateTypedNameReferences]
public sealed partial class AccountManagementTab : Control
{
    [Dependency] private readonly EntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    private IReadOnlyList<Entity<EconomyBankAccountComponent>> _accounts = default!;
    private readonly List<string> _jobs = new();
    private static readonly ProtoId<JobPrototype> _defaultJob = "Passenger";
    private EconomyBankAccountComponent? _currentAccount;
    private EconomyBankAccountSystemShared _bankAccountSystem = default!;
    private string _defaultJobName = string.Empty;
    private int _defaultJobIndex = -1;

    public Action<EconomyBankAccountComponent>? OnBlockAccountPressed;
    public Action<EconomyBankAccountComponent, string>? OnChangeNamePressed;
    public Action<EconomyBankAccountComponent, string>? OnChangeJob;
    public Action<EconomyBankAccountComponent, ulong>? OnChangeSalary;

    public bool Priveleged;

    public AccountManagementTab()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _bankAccountSystem = _entityManager.System<EconomyBankAccountSystemShared>();
        if (_prototypeManager.TryIndex(_defaultJob, out var defaultJobPrototype))
            _defaultJobName = Loc.GetString(defaultJobPrototype.Name);
        else
            _defaultJobName = _defaultJob;

        var jobs = _prototypeManager.EnumeratePrototypes<JobPrototype>().ToList();
        jobs.Sort((x, y) => string.Compare(x.LocalizedName, y.LocalizedName, StringComparison.CurrentCulture));
        foreach (var job in jobs)
        {
            if (!job.OverrideConsoleVisibility.GetValueOrDefault(job.SetPreference))
                continue;

            _jobs.Add(job.ID);
            JobPresetOptionButton.AddItem(Loc.GetString(job.Name), _jobs.Count - 1);
        }

        _defaultJobIndex = GetJobIndex(_defaultJob);
        if (_defaultJobIndex < 0)
            _defaultJobIndex = 0;

        SalaryAmountBox.AddLeftButton(-10, "-10");
        SalaryAmountBox.AddLeftButton(-1, "-1");
        SalaryAmountBox.AddRightButton(1, "+1");
        SalaryAmountBox.AddRightButton(10, "+10");
        SalaryAmountBox.SetButtonDisabled(true);

        UpdateAccountList();

        FindAccount.OnTextEntered += OnTextEnteredAccount;
        SalaryAmountBox.ValueChanged += OnSalaryValueChanged;

        BlockButton.OnPressed += _ =>
        {
            if (_currentAccount is null)
                return;

            OnBlockAccountPressed?.Invoke(_currentAccount);
        };
        ChangeNameButton.OnPressed += _ =>
        {
            if (_currentAccount is null || ChangeNameBox.Text.Length <= 0)
                return;

            OnChangeNamePressed?.Invoke(_currentAccount, ChangeNameBox.Text);
            ChangeNameBox.Clear();
        };
        JobPresetOptionButton.OnItemSelected += args =>
        {
            args.Button.SelectId(args.Id);

            var bankAccountSystem = _entityManager.System<EconomyBankAccountSystemShared>();
            if (bankAccountSystem.TryGetSalaryJobEntry(_jobs[args.Id], EconomyBankAccountSystemShared.DefaultSalariesPrototypeId, out var jobEntry))
                SalaryAmountBox.Value = (int)jobEntry.Value.Sallary;
        };
        ChangeSalaryInfoButton.OnPressed += _ =>
        {
            if (_currentAccount is null)
                return;

            var jobName = _currentAccount.JobName;
            var salary = _currentAccount.Salary;
            if (JobPresetOptionButton.SelectedId != _jobs.IndexOf(jobName.GetValueOrDefault()))
                OnChangeJob?.Invoke(_currentAccount, _jobs[JobPresetOptionButton.SelectedId]);
            if (SalaryAmountBox.Value != (int)salary.GetValueOrDefault())
                OnChangeSalary?.Invoke(_currentAccount, (ulong)SalaryAmountBox.Value);
        };
    }

    public void UpdateAccountList()
    {
        AccountList.Clear();
        var accounts = _bankAccountSystem.GetAccounts(EconomyBankAccountMask.All);
        _accounts = accounts.Values
            .Where(account => !_bankAccountSystem.IsCentralCommandAccount(account.Comp.AccountID))
            .ToList();

        FillList();
    }

    public void OnUpdateState(string? accountID,
                              string? accountName,
                              ulong? balance,
                              ulong? penalty,
                              bool? blocked,
                              bool? canReachPayDay,
                              string? jobName,
                              ulong? salary,
                              ulong? payrollSalary,
                              bool? payrollCanReach)
    {
        if (accountID is null || _currentAccount?.AccountID != accountID)
        {
            ClearCurrentAccount();
            return;
        }

        var lookupAccountId = accountID;
        AccountIdLabel.Text = accountID;
        AccountOwnerLabel.Text = accountName ?? "-";
        var accountBalance = balance is not null ? string.Format("{0:N0}", balance) : "-";
        AccountBalanceLabel.Text = accountBalance;
        var accountBlocked = blocked is not null ? (blocked.Value ? Loc.GetString("economybanksystem-management-console-management-block") : Loc.GetString("economybanksystem-management-console-management-unblock"))
                                          : "-";
        AccountBlockedLabel.Text = accountBlocked;
        EconomyBankAccountComponent? accountComp = null;
        if (lookupAccountId != null && _bankAccountSystem.TryGetAccount(lookupAccountId, out var foundAccount))
            accountComp = foundAccount.Value.Comp;
        _currentAccount = accountComp;

        var accountSalary = salary ?? 0;
        var displaySalary = payrollSalary ?? accountSalary;
        var displayReachable = payrollCanReach ?? canReachPayDay;
        AccountPaydayStatusLabel.Text = displayReachable is not null ? (displayReachable.Value ? Loc.GetString("economybanksystem-management-console-management-salary-reachable", ("salary", displaySalary)) : Loc.GetString("economybanksystem-management-console-management-salary-not-reachable", ("salary", displaySalary)))
                                                      : "-";
        var blockedButton = blocked is not null ? (blocked.Value ? Loc.GetString("economybanksystem-management-console-management-unblock-button") : Loc.GetString("economybanksystem-management-console-management-block-button"))
                                                : "-";
        BlockButton.Text = blockedButton;
        var salaryValue = accountComp is not null && IsReadOnlyAccount(accountComp) ? displaySalary : accountSalary;
        SalaryAmountBox.Value = (int) salaryValue;

        UpdateJobPreset(accountComp, jobName);
        UpdateButtons(Priveleged);
    }

    private void OnSelectAccount(ItemList.Item accountId)
    {
        if (accountId.Metadata is not EconomyBankAccountComponent account)
            return;

        _currentAccount = account;
        FillAccountInfo(account);
        UpdateButtons(Priveleged);
    }

    private void OnSalaryValueChanged(ValueChangedEventArgs args)
    {
        // what shitcode does to a man
        SalaryAmountBox.ValueChanged -= OnSalaryValueChanged;
        SalaryAmountBox.Value = Math.Max(0, args.Value);
        SalaryAmountBox.ValueChanged += OnSalaryValueChanged;
    }

    private void OnTextEnteredAccount(LineEdit.LineEditEventArgs eventArgs)
    {
        AccountList.Clear();
        var upText = eventArgs.Text.ToUpper();
        foreach (var (key, value) in _accounts)
        {
            var fieldName = FormFieldName(value);
            if (fieldName.Contains(upText))
            {
                var field = AccountList.AddItem(fieldName);
                field.Metadata = value;
                field.OnSelected += OnSelectAccount;
            }
        }
        if (AccountList.Count == 0)
        {
            AccountList.AddItem("No data acquired");
            return;
        }
        AccountList.SortItemsByText();
    }

    private void FillList()
    {
        foreach (var (key, value) in _accounts)
        {
            var field = AccountList.AddItem(FormFieldName(value));
            field.Metadata = value;
            field.OnSelected += OnSelectAccount;
        }

        AccountList.SortItemsByText();
    }

    private string FormFieldName(EconomyBankAccountComponent account)
    {
        return account.AccountID + " - " + account.AccountName;
    }

    private bool IsReadOnlyAccount(EconomyBankAccountComponent account)
    {
        return _bankAccountSystem.IsRestrictedDepartmentAccount(account);
    }

    private string GetRestrictedJobText(EconomyBankAccountComponent account)
    {
        var key = _bankAccountSystem.IsDepartmentCashAccount(account)
            ? "economybanksystem-management-console-management-job-placeholder-cash"
            : "economybanksystem-management-console-management-job-placeholder-department";
        return Loc.GetString(key);
    }

    private void UpdateJobPreset(EconomyBankAccountComponent? account, string? jobName)
    {
        if (_defaultJobIndex >= 0)
            JobPresetOptionButton.SetItemText(_defaultJobIndex, _defaultJobName);

        if (account != null && IsReadOnlyAccount(account))
        {
            if (_defaultJobIndex >= 0)
            {
                JobPresetOptionButton.SetItemText(_defaultJobIndex, GetRestrictedJobText(account));
                JobPresetOptionButton.SelectId(_defaultJobIndex);
            }
            return;
        }

        JobPresetOptionButton.SelectId(GetJobIndex(jobName));
    }

    private int GetJobIndex(string? jobName)
    {
        var jobIndex = jobName is not null ? _jobs.IndexOf(jobName) : _jobs.IndexOf(_defaultJob);
        return jobIndex < 0 ? _jobs.IndexOf(_defaultJob) : jobIndex;
    }

    private void UpdateButtons(bool priveleged)
    {
        var disabled = _currentAccount is null || !priveleged;
        var readOnly = _currentAccount is not null && IsReadOnlyAccount(_currentAccount);

        BlockButton.Disabled = disabled;
        ChangeNameButton.Disabled = disabled || readOnly;
        JobPresetOptionButton.Disabled = disabled || readOnly;
        SalaryAmountBox.LineEditDisabled = disabled || readOnly;
        SalaryAmountBox.SetButtonDisabled(disabled || readOnly);
        ChangeSalaryInfoButton.Disabled = disabled || readOnly;
    }

    private void ClearCurrentAccount()
    {
        AccountIdLabel.Text = "-";
        AccountOwnerLabel.Text = "-";
        AccountBalanceLabel.Text = "-";
        AccountBlockedLabel.Text = "-";
        AccountPaydayStatusLabel.Text = "-";
        BlockButton.Text = "-";
        SalaryAmountBox.Value = 0;

        _currentAccount = null;
        UpdateJobPreset(null, null);
        UpdateButtons(Priveleged);
    }

    private void FillAccountInfo(EconomyBankAccountComponent account)
    {
        AccountIdLabel.Text = account.AccountID;
        AccountOwnerLabel.Text = account.AccountName;
        var balance = account.Balance;
        AccountBalanceLabel.Text = balance.ToString("N0") ?? "-";
        AccountBlockedLabel.Text = account.Blocked ? Loc.GetString("economybanksystem-management-console-management-block") :
                                                     Loc.GetString("economybanksystem-management-console-management-unblock");
        var salary = account.Salary ?? 0;
        var reachable = account.CanReachPayDay;
        AccountPaydayStatusLabel.Text = reachable is not null ? (reachable.Value ? Loc.GetString("economybanksystem-management-console-management-salary-reachable", ("salary", salary)) :
                                                                  Loc.GetString("economybanksystem-management-console-management-salary-not-reachable", ("salary", salary)))
                                                   : "-";
        BlockButton.Text = account.Blocked ? Loc.GetString("economybanksystem-management-console-management-unblock-button") :
                                             Loc.GetString("economybanksystem-management-console-management-block-button");
        UpdateJobPreset(account, account.JobName);
        SalaryAmountBox.Value = (int)salary;
    }
}
